version: 2
registries:
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: floryn90
    password: ${{ secrets.DOCKER_TOKEN }}  # Make sure the token is properly stored in GitHub secrets

updates:
  - package-ecosystem: "docker"
    directories: 
      - /src/docker/               # Main Dockerfile directory (if it's in the root)
      - /src/docker/_base/         # Subdirectories containing Dockerfiles
      - /src/docker/_imports/
      - /src/docker/alpine/
      - /src/docker/alpine-ext/
      - /src/docker/busybox/
      - /src/docker/debian/
      - /src/docker/debian-ext/
      - /src/docker/ubuntu/
      - /src/docker/ubuntu-ext/
    registries:
      - dockerhub  # Docker registry to use for updates
    target-branch: master  # The branch where Dependabot should create PRs
    schedule:
      interval: "daily"  # The frequency of updates (can also be 'weekly', 'monthly', etc.)
    commit-message:
      prefix: "fix"  # Prefix for the commit message in Dependabot PRs (e.g., 'update', 'chore', etc.)
