name: Install required dependencies
description: Install required build dependencies
runs:
  using: composite
  steps:
    - name: Install deps
      shell: bash
      run: |-
        sudo apt update && sudo apt install curl gpg -y
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt-get install dirmngr -y
        sudo apt-get update
        sudo apt-get install gh build-essential wget git jq -y
        sudo apt-get autoclean
        sudo apt-get autoremove
        sudo rm -rf /var/lib/apt/lists/*
