name: "Base"

images:
  base:
    target: base
    alias:
      - $(VERSION)-base
    tests:
      - defaultuser

tests:    
  defaultuser:
    entrypoint: whoami
    command: $USER
    expected: hugo