name: Debian (standard)

images:
  # Debian + Hugo
  debian:
    target: debian
    edge: true
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-debian
    tests:
      - hugo
      - defaultuser

  # Debian + Hugo + CI
  debian-ci:
    target: debian--ci
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-debian-ci
    tests:
      - defaultuser

  # Debian + Hugo + Onbuild
  debian-onbuild:
    target: debian--onbuild
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-debian-onbuild
    tests:
      - defaultuser

tests:
  hugo:
    command: version
    expected: hugo
    
  defaultuser:
    entrypoint: whoami
    command: $USER
    expected: hugo