name: Docker Image build CI

on:
  pull_request:
    branches: 
    - master
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

permissions: 
  contents: write
  pull-requests: write
  discussions: write
  issues: write

jobs:
  build:
    runs-on: floryn90-runners
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:

      - name: Clean Workspace
        uses: AutoModality/action-clean@v1
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build essential
        uses: ./.github/actions/install_deps  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: floryn90
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Prepare
        shell: bash
        run: make prepare

      - name: Upload generated Dockerfile 
        uses: actions/upload-artifact@v4
        with:
          name: Dockerfile
          path: target/bundle/Dockerfile

  dependabot-scan:
    needs: build
    runs-on: floryn90-runners
    steps:
      - name: Download generated Dockerfile
        uses: actions/download-artifact@v4
        with:
          name: Dockerfile

      - name: Run Dependabot (Manually trigger if needed)
        run: |
          curl -X POST -H "Authorization: token ${{  secrets.TOKEN_GITHUB  }}" \
          -d '{"event_type": "dependabot-trigger"}' \
          https://api.github.com/repos/${{ github.repository }}/dispatches