name: SonarCloud analysis

on:
  push:
    branches: 
    - release/*
    paths-ignore:
      - '.github/**'    
  pull_request:
    branches: 
    - master
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: floryn90-runners
    steps:

      - name: Checkout
        uses: actions/checkout@v4      

      - name: Install build essential
        uses: ./.github/actions/install_deps  

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the sonarcloud scanner
          args: >
            -Dsonar.projectKey=floryn90
            -Dsonar.organization=florin-lungu
            -Dsonar.sources=src 
            